version: "3"

volumes:
  tvsd_web_local_postgres_data: {}
  tvsd_web_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tvsd_web_local_django
    container_name: tvsd_web_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django.env
      - ./.envs/.local/.postgres.env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: tvsd_web_production_postgres
    container_name: tvsd_web_local_postgres
    volumes:
      - tvsd_web_local_postgres_data:/var/lib/postgresql/data
      - tvsd_web_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres.env

  docs:
    image: tvsd_web_local_docs
    container_name: tvsd_web_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django.env
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./tvsd_web:/app/tvsd_web:z
      - ./rewards:/app/rewards:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: tvsd_web_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: tvsd_web_local_redis

  celeryworker:
    <<: *django
    image: tvsd_web_local_celeryworker
    container_name: tvsd_web_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: tvsd_web_local_celerybeat
    container_name: tvsd_web_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: tvsd_web_local_flower
    container_name: tvsd_web_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  vite:
    build:
      context: .
      dockerfile: ./compose/local/vite/Dockerfile
    image: my_awesome_vue_project_local_vite
    container_name: my_awesome_vue_project_local_vite
    depends_on:
      - django
    volumes:
      - .:/app:z
      - /app/vue_frontend/node_modules
    command: vite dev
    ports:
      - "5173:5173"
